pipeline {
    agent { label 'jenkins-test-agent' }
    stages {
        stage('Build') {
            steps {
                script {
                    withCredentials([file(credentialsId: 'minikube-kubeconfig', variable: 'KUBECONFIG')]) {
                        sh 'export KUBECONFIG=$KUBECONFIG && eval $(minikube -p minikube docker-env)'
                        docker.build('backend-image', '-f hello-world-backend/Dockerfile .')
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    withCredentials([file(credentialsId: 'minikube-kubeconfig', variable: 'KUBECONFIG')]) {
                        sh 'export KUBECONFIG=$KUBECONFIG && helm install backend-chart ./charts/backend-chart --namespace backend --set image.repository=backend-image --set image.tag=latest'
                    }
                }
            }
        }
    }
}
