pipeline {
    agent { label 'jenkins-test-agent' }
    stages {
        stage('Build') {
            steps {
                script {
                    docker.build('backend-image', '-f hello-world-backend/Dockerfile .')
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    withKubeConfig(caCertificate: '', clusterName: '', contextName: '', credentialsId: '', namespace: 'backend', serverUrl: '') {
                        sh 'helm install backend-chart ./backend-chart --namespace backend --set image.repository=backend-image --set image.tag=latest'
                    }
                }
            }
        }
    }
}
