# Default values for frontend-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

base-chart:
  global:
    fullnameOverride: frontend
  envVarName: BACKEND_HOST
  envVarValue: backend-service.backend.svc.cluster.local
  nameOverride: frontend-chart
  chartVersion: 0.1.0
  image:
    repository: frontend-image
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
    protocol: TCP
    name: frontend-chart
    selectorLabels:
      app: frontend-chart
  ingress:
    enabled: true
    hosts:
      - host: frontend.local
        paths:
          - path: /
            pathType: ImplementationSpecific



