# Default values for backend-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

base-chart:
  global:
    fullnameOverride: backend
  nameOverride: backend-chart
  chartVersion: 0.1.0
  image:
    repository: haykhs/backend-image
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
    protocol: TCP
    name: backend-chart
    selectorLabels:
      app: backend-chart
  ingress:
    enabled: false