pipeline {
    agent { label 'jenkins-test-agent' }
    stages {
        stage('Build') {
            steps {
                script {
                    docker.build('frontend-image', '-f hello-world-frontend/Dockerfile .')
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    withCredentials([file(credentialsId: 'minikube-kubeconfig', variable: 'KUBECONFIG')]) {
                        sh 'export KUBECONFIG=$KUBECONFIG && helm install frontend-chart ./charts/./frontend-chart --namespace frontend --set image.repository=frontend-image --set image.tag=latest'
                    }
                }
            }
        }
    }
}
