pipeline {
    agent { label 'jenkins-test-agent' }
    stages {
        stage('Build') {
            steps {
                script {
                    withCredentials([file(credentialsId: 'minikube-kubeconfig', variable: 'KUBECONFIG')]) {
                        sh '''
                            export KUBECONFIG=$KUBECONFIG
                            eval $(minikube -p minikube docker-env)
                            docker build -t frontend-image:latest -f hello-world-frontend/Dockerfile .
                        '''
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    withCredentials([file(credentialsId: 'minikube-kubeconfig', variable: 'KUBECONFIG')]) {
                        sh 'export KUBECONFIG=$KUBECONFIG && helm upgrade frontend-chart ./charts/./frontend-chart --namespace frontend --set image.repository=frontend-image --set image.tag=latest'
                    }
                }
            }
        }
    }
}
