apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/HaykHSS/helmChartsApp.git'
    targetRevision: HEAD
    path: charts/backend-chart
    helm:
      values: |
        base-chart:
          image:
            tag: "1.0.0"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: backend
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
