apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: build-and-sync-
  name: build-and-sync-workflow
spec:
  entrypoint: build-and-sync
  volumes:
  - name: workdir
    emptyDir: {}
  templates:
  - name: build-and-sync
    steps:
    - - name: build-image
        template: build-image
    - - name: trigger-argocd-sync
        template: trigger-argocd-sync

  - name: build-image
    container:
      image: docker:latest
      command: [sh, -c]
      args: [
        "printenv && docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && \
        docker build -t haykhs/backend-image:latest . && \
        docker push haykhs/backend-image:latest"
      ]
      env:
      - name: DOCKER_USERNAME
        valueFrom:
          secretKeyRef:
            name: docker-credentials
            key: username
      - name: DOCKER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: docker-credentials
            key: password
      volumeMounts:
      - name: workdir
        mountPath: /mnt/data

  - name: trigger-argocd-sync
    container:
      image: argoproj/argocd-cli:v2.0.0
      command: [sh, -c]
      args: [
        "argocd app sync my-app --server argocd-server.argocd.svc.cluster.local:443 --auth-token $ARGOCD_AUTH_TOKEN"
      ]
      env:
      - name: ARGOCD_AUTH_TOKEN
        valueFrom:
          secretKeyRef:
            name: argocd-secret
            key: admin.password
      volumeMounts:
      - name: workdir
        mountPath: /mnt/data
