apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-creator-binding
  namespace: argo
subjects:
- kind: ServiceAccount
  name: operate-workflow-sa
  namespace: argo-events
roleRef:
  kind: Role
  name: workflow-creator-role
  apiGroup: rbac.authorization.k8s.io
